package KieRule;
import com.damian.drools.model.Order;
import com.damian.drools.enums.CardType;


rule "HNB"
when
orderObject : Order(cardType == CardType.HNB)
then
orderObject.setDiscount(10);
orderObject.setStatus("This rule was fired by Drools!");
end

rule "HSBC"
when
orderObject : Order(cardType == CardType.HSBC)
then
orderObject.setDiscount(20);
orderObject.setStatus("This rule was fired by Drools!");
end

rule "COMBANK"
when
orderObject : Order(cardType == CardType.COMBANK)
then
orderObject.setDiscount(30);
orderObject.setStatus("This rule was fired by Drools!");
end


rule "NSB"
when
orderObject : Order(cardType == CardType.NSB && orderObject.price > 1000)
then
orderObject.setDiscount(40);
orderObject.setStatus("This rule was fired by Drools!");
end
